version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    container_name: auth-service
#    command: bash -c "yoyo init --database postgresql+psycopg://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME} migrations && yoyo develop && python -m app"

    command: bash -c "yoyo develop && python -m app"
    ports:
      - "50052:50052"
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    container_name: auth-postgres
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "2345:5432"

#  sonarqube:
#    container_name: "sonarqube"
#    image: "sonarqube:9.9.1-community"
#    volumes:
#      - ./sonarqube/extensions:/opt/sonarqube/extensions
#      - ./sonarqube/logs:/opt/sonarqube/logs
#      - ./sonarqube/data:/opt/sonarqube/data
#    expose:
#      - "9000"
#    ports:
#      - "9000:9000"
